### ISSUE TITLE
Visually differentiate pinned messages

### ISSUE THREAD

**Issue by corincewang** [CMU-313/spring24-nodebb-sss#6]

**Comment by viviannna** [comment]
Estimated effort: 20 hours
Need to learn typescript, get familiar with the code base, and draft out the changes. 
Acceptance Criteria: At minimum, at least a colored background to easily highlight important messages. 
Maybe test using https://accessibe.com/ or some other method of deducting visual contrast.

**Comment by viviannna** [comment]
Need to create one section for pinned messages created separate from the other regular replies.
